In [1]:
print("Hello")

Hello


In [2]:
print("Hello")

Hello


In [3]:
a=[1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [4]:
type(a)

list

In [5]:
import numpy as np

In [6]:
c=np.array(a)
print(c)

[1 2 3 4 5]


In [7]:
type(c)

numpy.ndarray

In [9]:
c.ndim

1

In [11]:
a=[[1,2,3],[3,4,5]]
type(a)

list

In [12]:
b= np.array(a)
print(b)

[[1 2 3]
 [3 4 5]]


In [13]:
type(b)

numpy.ndarray

In [14]:
b.ndim

2

In [15]:
m=[[[1,2,3],[3,4,5],[7,8,9]]]
type(m)

list

In [16]:
n= np.array(m)
print(n)

[[[1 2 3]
  [3 4 5]
  [7 8 9]]]


In [17]:
type(n)

numpy.ndarray

In [18]:
n.ndim

3

In [19]:
n.shape

(1, 3, 3)

In [20]:
n.size

9

In [21]:
n.dtype

dtype('int64')

In [22]:
n.itemsize

8

In [23]:
n.data

In [24]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [25]:
np.zeros(n.shape)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])